CREATE SCHEMA x6;

CREATE TABLE x6.product
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR        NOT NULL,
    price      DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    used_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);